project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "*.md"

website:
  navbar:
    logo: "assets/images/SU_logo.png"
    right:
      - text: "HOME"
        href: "Home.html"
      - text: "CONTENTS"
        href: "contents.html"


  site-url: "https://kmgjan.github.io/MED/"



knitr:
  opts_chunk:
    results: hold

execute:
  eval: true
  echo: true
  warning: false
  message: false
  freeze: auto
