
project:
  type: website
  output-dir: docs
  

  

website:
  title: "Marine Ecosystem Dynamics - 2023"
  favicon: assets/images/favicon.svg
  navbar:
    alignment: center
    background: light
    border: true
    logo: assets/images/logo.png
    right:
      - href: index.html
        text: HOME
      - href: about.html
        text: ABOUT
      - href: program.html
        text: MATERIAL
      - icon: "github"
        href: "https://github.com/KMGJan/MED"
        target: "_blank"
      - icon: envelope
        href: mailto:kinlan.jan@su.se
        
  page-footer:
    border: false
    left: "![](assets/images/SU_black.svg){height=2.5em style=margin-bottom:-1px;}"
    center: "Marine Ecosystem Dynamics [2023](about.html) | [Lab group](https://winderlab.com/){target=_blank}"
    right: "Published with [Quarto](https://quarto.org/){target=_blank}"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    self-contained: true
