project:
  type: website
  output-dir: docs
  

  

website:
  title: "Introduction to R - Marine Ecosystem Dynamics"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: about.html
        text: About
      - href: program.html
        text: Program

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



